### ISSUE TITLE
generate XLA

### ISSUE THREAD

**Issue by sycamoreoak** [EnzymeAD/rust#172]
generate XLA, please!

**Comment by ZuseZ4** [comment]
This project develops a Rust frontend for Enzyme.
Developing an XLA backend for Rustc would be an independent work.
Due to the high level nature of XLA it probably also wouldn't be able to reuse rustc_codegen_ssa and therefore be a larger effort than rustc_codegen_gcc and rustc_codegen_cranelift, which are already large project. So this is out of scope here.
